Fix various incompatible pointer types.
This patch fixes a bunch of type errors like the following, by casting
the expected types, working around gcc warnings that have gone fatal
in gcc 14:

	src/index.c:1263:59: error: passing argument 2 of ‘ti_querys_2d_multi’ from incompatible pointer type
	+[-Wincompatible-pointer-types]
	1263 |          sequential_iter_t *siter = ti_querys_2d_multi(t, regions, n_sub_list);
	     |                                                           ^~~~~~~
	     |                                                           |
	     |                                                           char **
	src/pairix.h:131:73: note: expected ‘const char **’ but argument is of type ‘char **’

Note the pointer returned by ti_iter_first cast to "int" in function
ti_query_2d_tid, in src/index.c, feels like an incident waiting to
happen, but the function is expected to return addresses or error
codes, so it is left as-is due to lack of better idea for the moment.

Signed-off-by: Étienne Mollier <emollier@debian.org>